# Generated by Django 2.0.2 on 2019-03-19 14:00

from django.db import migrations, models
import django.utils.timezone

import pymysql

pymysql.install_as_MySQLdb()
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_password', models.CharField(max_length=10)),
                ('c_phone_no', models.IntegerField()),
                ('c_email_id', models.EmailField(max_length=50)),
                ('c_address', models.CharField(max_length=50)),
                ('c_photo', models.ImageField(default='static/images/bg-01.jpg', upload_to='static/images/cust_photoes')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=20)),
                ('t_id', models.CharField(max_length=20)),
                ('order_review', models.FloatField(default=0.0)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='tasker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=20)),
                ('t_password', models.CharField(max_length=10)),
                ('t_phone_no', models.IntegerField()),
                ('t_email', models.CharField(max_length=20)),
                ('t_type', models.CharField(max_length=15)),
                ('t_location', models.CharField(max_length=20)),
                ('t_rupee', models.IntegerField()),
                ('t_address', models.CharField(max_length=50)),
                ('t_rate', models.CharField(max_length=5)),
                ('t_photo', models.ImageField(default='static/images/bg-01.jpg', upload_to='static/images/tasker_photoes')),
            ],
        ),
    ]
