# Generated by Django 2.0.2 on 2019-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtoZdelivery', '0002_orders_t_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='t_rupee',
            field=models.IntegerField(default=0),
        ),
    ]
