# Generated by Django 2.0.2 on 2019-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtoZdelivery', '0003_orders_t_rupee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
    ]
