# Generated by Django 2.0.2 on 2019-03-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtoZdelivery', '0004_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_address',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
