# Generated by Django 2.0.2 on 2019-03-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtoZdelivery', '0005_orders_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasker',
            name='t_rate',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
